baseURL = "https://gomes-fdr.github.io/"
languageCode = "pt-br"
defaultContentLanguage = "pt"
author = "Fabiano da Rosa Gomes"
title = "Fabiano Gomes"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright notice | Some rights reserved"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["software", "linux", "development"]

	# Add meta description in head part
	description = "My personal binary log"

	# Add pagetitle to homepage <title> tag
	pagetitle = "All about me"

	# Add a subtitle to your website
	subtitle = "Software Developer"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/images/avatar.png"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path is static/css/)
	#customCSS = "custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Lists"
url = "/lists"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://www.github.com/gomes-fdr"

[[params.social]]
name = "Linkedin"
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/gomes-fdr"

[[params.social]]
name = "email"
icon = "far fa-envelope"
url = "mailto:gomes.fdr@gmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

[[params.social]]
name = "Mastodon"
lcon = "fab fa-mastodon"
url = "https://bolha.us/web/@gomes_fdr"
